trained_model: 'scanDoc/weights/craft_mlt_25k.pth'          # pretrained model   craft_mlt_25k.pth
text_threshold: 0.7                                 # text confidence threshold
low_text: 0.4                                       # text low-bound score
link_threshold: 0.4                                 # link confidence threshold
cuda: False                                          # Use cuda for inference
canvas_size: 320                                    # image size for inference
mag_ratio: 1.5                                      # image magnification ratio
poly: False                                         # enable polygon type
show_time: False                                    # show processing time
test_folder: 'data'
refine: False                                       # enable link refiner
refiner_model: 'scanDoc/weights/craft_refiner_CTW1500.pth'  # pretrained refiner model  craft_refiner_CTW1500
